#ifndef TOOLQUADDRAW_H__
#define TOOLQUADDRAW_H__

enum
{
    QUADDRAW_GROUP_TOOL             = 2030,
    QUADDRAW_ACTIVE_TOOL            = 2031,
    QUADDRAW_TOOL_QUAD              = 0,
    QUADDRAW_TOOL_MOVE              = 3,
    QUADDRAW_TOOL_KNIFE             = 1,
    QUADDRAW_TOOL_MULTICUT          = 2,
    QUADDRAW_TOOL_DELETE            = 4,
    QUADDRAW_TOOL_GRAB              = 5,
    QUADDRAW_TOOL_PIN               = 6,
    QUADDRAW_DELETE_UNCONNECTED     = 2032,
    QUADDRAW_SNAP_ALL_TO_SURFACE    = 2033,

    QUADDRAW_GROUP_PIN              = 2050,
    QUADDRAW_PIN_RADIUS             = 2051,
    QUADDRAW_PIN_COLOR              = 2052,
    QUADDRAW_PIN_VISIBLE_ONLY       = 2053,
    QUADDRAW_PIN_BORDER             = 2054,
    QUADDRAW_PIN_ALL                = 2055,
    QUADDRAW_UNPIN_ALL              = 2056,
    QUADDRAW_INVERT_PINS            = 2057,

    QUADDRAW_GROUP_DISPLAY          = 2000,
    QUADDRAW_DISABLE_CUSTOM_SHADING = 2006,
    QUADDRAW_DISABLE_XRAY           = 2007,
    QUADDRAW_DISABLE_POINT_XRAY     = 2007,
    QUADDRAW_MESH_COLOR             = 2001,
    QUADDRAW_FACE_OPACITY           = 2002,
    QUADDRAW_WIRE_COLOR             = 2003,
    QUADDRAW_LINE_WIDTH             = 2004,
    QUADDRAW_POINT_SIZE             = 2005,

    QUADDRAW_GROUP_INTERACTIVE   = 2010,
    QUADDRAW_BORDER_EXTRUDE_LMB  = 2015,
    QUADDRAW_CUT_THROUGH         = 2016,
    QUADDRAW_CUT_INFINITE        = 2017,
    QUADDRAW_PREVIEW_COLOR       = 2011,
    QUADDRAW_CUT_COLOR           = 2012,
    QUADDRAW_HIGHLIGHT_COLOR     = 2013,
    QUADDRAW_HOVER_LINE_WIDTH    = 2014,

    QUADDRAW_GROUP_RELAX         = 2020,
    QUADDRAW_RELAX_RADIUS        = 2021,
    QUADDRAW_RELAX_STRENGTH      = 2022,
    QUADDRAW_RELAX_MODE          = 2023,
    QUADDRAW_RELAX_MODE_AUTOLOCK = 0,
    QUADDRAW_RELAX_MODE_INTERIOR = 1,
    QUADDRAW_RELAX_MODE_BORDER   = 2,
    QUADDRAW_RELAX_MODE_ALL      = 3,
    QUADDRAW_RELAX_VISIBLE_ONLY  = 2024,

    QUADDRAW_GROUP_GRAB             = 2040,
    QUADDRAW_GRAB_RADIUS            = 2041,
    QUADDRAW_GRAB_INTENSITY         = 2042,
    QUADDRAW_GRAB_FALLOFF           = 2043,
    QUADDRAW_GRAB_FALLOFF_SMOOTH    = 0,
    QUADDRAW_GRAB_FALLOFF_LINEAR    = 1,
    QUADDRAW_GRAB_FALLOFF_SPHERICAL = 2,
    QUADDRAW_GRAB_FALLOFF_SHARP     = 3,
    QUADDRAW_GRAB_VISIBLE_ONLY      = 2044
};

#endif // TOOLQUADDRAW_H__
