#ifndef TOOLQUADDRAW_H__
#define TOOLQUADDRAW_H__

enum
{
    QUADDRAW_GROUP_DISPLAY          = 2000,
    QUADDRAW_DISABLE_CUSTOM_SHADING = 2006,
    QUADDRAW_DISABLE_POINT_XRAY     = 2007,
    QUADDRAW_MESH_COLOR             = 2001,
    QUADDRAW_FACE_OPACITY           = 2002,
    QUADDRAW_WIRE_COLOR             = 2003,
    QUADDRAW_LINE_WIDTH             = 2004,
    QUADDRAW_POINT_SIZE             = 2005,

    QUADDRAW_GROUP_INTERACTIVE   = 2010,
    QUADDRAW_PREVIEW_COLOR       = 2011,
    QUADDRAW_CUT_COLOR           = 2012,
    QUADDRAW_HIGHLIGHT_COLOR     = 2013,
    QUADDRAW_HOVER_LINE_WIDTH    = 2014,

    QUADDRAW_GROUP_RELAX         = 2020,
    QUADDRAW_RELAX_RADIUS        = 2021,
    QUADDRAW_RELAX_STRENGTH      = 2022,
    QUADDRAW_RELAX_MODE          = 2023,
    QUADDRAW_RELAX_MODE_AUTOLOCK = 0,
    QUADDRAW_RELAX_MODE_INTERIOR = 1,
    QUADDRAW_RELAX_MODE_BORDER   = 2,
    QUADDRAW_RELAX_MODE_ALL      = 3,
    QUADDRAW_RELAX_VISIBLE_ONLY  = 2024
};

#endif // TOOLQUADDRAW_H__
