CONTAINER toolquaddraw
{
    NAME toolquaddraw;
    INCLUDE ToolBase;

    GROUP MDATA_MAINGROUP
    {
        GROUP QUADDRAW_GROUP_DISPLAY
        {
            DEFAULT 1;

            COLOR QUADDRAW_MESH_COLOR       { }
            REAL  QUADDRAW_FACE_OPACITY     { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
            COLOR QUADDRAW_WIRE_COLOR       { }
            REAL  QUADDRAW_LINE_WIDTH       { MIN 1.0; MAX 10.0; MINSLIDER 1.0; MAXSLIDER 5.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
            REAL  QUADDRAW_POINT_SIZE       { MIN 1.0; MAX 10.0; MINSLIDER 1.0; MAXSLIDER 10.0; STEP 0.5; CUSTOMGUI REALSLIDER; }
        }

        GROUP QUADDRAW_GROUP_INTERACTIVE
        {
            DEFAULT 1;

            COLOR QUADDRAW_PREVIEW_COLOR    { }
            COLOR QUADDRAW_CUT_COLOR        { }
            COLOR QUADDRAW_HIGHLIGHT_COLOR  { }
            REAL  QUADDRAW_HOVER_LINE_WIDTH { MIN 1.0; MAX 10.0; MINSLIDER 1.0; MAXSLIDER 6.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
        }

        GROUP QUADDRAW_GROUP_RELAX
        {
            DEFAULT 1;

            LONG QUADDRAW_RELAX_MODE
            {
                CYCLE
                {
                    QUADDRAW_RELAX_MODE_AUTOLOCK;
                    QUADDRAW_RELAX_MODE_INTERIOR;
                    QUADDRAW_RELAX_MODE_BORDER;
                    QUADDRAW_RELAX_MODE_ALL;
                }
            }

            BOOL  QUADDRAW_RELAX_VISIBLE_ONLY { }
            REAL  QUADDRAW_RELAX_RADIUS   { MIN 5.0; MAX 300.0; MINSLIDER 10.0; MAXSLIDER 150.0; STEP 5.0; CUSTOMGUI REALSLIDER; }
            REAL  QUADDRAW_RELAX_STRENGTH { MIN 0.05; MAX 1.0; MINSLIDER 0.05; MAXSLIDER 1.0; STEP 0.05; CUSTOMGUI REALSLIDER; }
        }
    }
}
